version: '2'

services:
  postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: mobydock
      POSTGRES_PASSWORD: yourpassword
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:3.2-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis:/var/lib/redis/data

  mobydock:
    build: .
    depends_on:
      - 'postgres'
    volumes:
      - .:/mobydock
    ports:
      - '8000:8000'
    env_file:
      - .env

volumes:
  postgres:
  redis:
